backend:
  name: git-gateway
  branch: main

media_folder: "images" 

collections:
  - name: "content"
    label: "Контент страниц"
    files:
      - file: "config.json"
        label: "Основной контент сайта"
        name: "config"
        fields:
          - { label: "Шапка", name: "header", widget: "object", fields: [
              { label: "Название (Логотип)", name: "logoText", widget: "string" },
              { label: "Слоган", name: "slogan", widget: "string" }
            ]}
          - { label: "Главный экран", name: "hero", widget: "object", fields: [
              { label: "Главный заголовок", name: "headline", widget: "string" },
              { label: "Текст на кнопке", name: "callToAction", widget: "string" },
              { label: "Фоновое изображение", name: "backgroundImage", widget: "image" }
            ]}
          - { label: "Коллекция", name: "collection", widget: "object", fields: [
              { label: "Заголовок секции", name: "title", widget: "string" },
              { label: "Товары", name: "items", widget: "list", fields: [
                  { label: "ID", name: "id", widget: "uuid", hide: true },
                  { label: "Название товара", name: "name", widget: "string" },
                  { label: "Описание", name: "description", widget: "text" },
                  { 
                    label: "3D Модель (.glb)", 
                    name: "model_glb", 
                    widget: "file", 
                    required: false,
                    media_folder: "model" # Указываем, что 3D модели хранятся в папке /model
                  },
                  { 
                    label: "Фотографии", 
                    name: "images", 
                    widget: "image", 
                    multiple: true, 
                    media_library: { config: { multiple: true } } 
                  },
                  { label: "Характеристики", name: "characteristics", widget: "object", fields: [
                      { label: "Высота", name: "Высота", widget: "string", required: false },
                      { label: "Ширина", name: "Ширина", widget: "string", required: false },
                      { label: "Глубина", name: "Глубина", widget: "string", required: false },
                      { label: "Материал", name: "Материал", widget: "string", required: false }
                    ]}
                ]}
            ]}
          - { label: "О нас", name: "about", widget: "object", fields: [
              { label: "Заголовок", name: "title", widget: "string" },
              { label: "Текст", name: "text", widget: "markdown" }
            ]}
          - { label: "3D Модель (в панели)", name: "model", widget: "object", fields: [
              { label: "Заголовок", name: "title", widget: "string" },
              { label: "Под-заголовок", name: "text", widget: "string" }
            ]}
          - { label: "Контакты", name: "contact", widget: "object", fields: [
              { label: "Заголовок", name: "title", widget: "string" },
              { label: "Адрес", name: "address", widget: "string" },
              { label: "Текст на кнопке формы", name: "formButtonText", widget: "string" }
            ]}
          - { label: "Футер", name: "footer", widget: "object", fields: [
              { label: "Копирайт", name: "copyright", widget: "string" }
            ]}